# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Instagram23' do
	pod 'Alamofire', '~> 4.4’
	pod 'AlamofireImage', '~> 3.1'
	pod 'SwiftyJSON'

  target 'Instagram23Tests' do
    inherit! :search_paths

    pod 'Alamofire', '~> 4.4’
    pod 'AlamofireImage', '~> 3.1'
    pod 'SwiftyJSON'
  end

end
